# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deployment Workflow

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    steps:
      - name: Fetching Changes from Github
        id: step_one
        run: |
          git pull
      - name: Stage 1 - Bringing up the service 
        id: step_two
        run: |
          docker compose -f docker-compose.yml up --build --detach
      - name: Stage 2 - Prune the docker system [ Removing all unnecessary docker assets]
        id: step_three
        run: |
          docker system prune --all --force
